import 'package:flutter/material.dart';

final ValueNotifier<Locale> ideaRadarLocale = ValueNotifier<Locale>(const Locale('en'));
const supportedIdeaRadarLocales = <Locale>[Locale('en'), Locale('ro')];

String tr(BuildContext context, String key) {
  final code = Localizations.localeOf(context).languageCode;
  return (_translations[code] ?? _translations['en']!)[key] ??
      _translations['en']![key] ??
      key;
}

const _translations = <String, Map<String, String>>{
  'en': {
    'app_title': 'Idea Tracker',
    'tagline': 'From idea to opportunity.',
    'tagline_detail': 'Capture, evaluate, and develop ideas with evidence.',
    'overview': 'Overview',
    'all_ideas': 'All ideas',
    'validated': 'Validated',
    'ideas': 'Ideas',
    'of': 'of',
    'review': 'Review',
    'new_idea': 'New idea',
    'archived_ideas': 'Archived ideas',
    'filter_sort': 'Filter and sort ideas',
    'search_ideas': 'Search ideas',
    'language': 'Language',
    'english': 'English',
    'romanian': 'Română',
    'idea_radar_ready': 'Your idea radar is ready',
    'add_first_idea_desc': 'Add your first idea and evaluate its potential.',
    'add_first_idea': 'Add your first idea',
    'no_filter_results': 'No ideas match these filters.',
    'clear_filters': 'Clear filters',
    'try_again': 'Try again',
    'idea_details': 'Idea details',
    'edit_idea': 'Edit idea',
    'more_actions': 'More actions',
    'archive_idea': 'Archive idea',
    'restore_idea': 'Restore idea',
    'archive': 'Archive',
    'restore': 'Restore',
    'delete_idea': 'Delete idea',
    'opportunity_score': 'Opportunity score',
    'not_evaluated': 'Not evaluated',
    'assumption_radar': 'Assumption Radar',
    'assumption_radar_subtitle': 'See what still needs to be proven',
    'research_notes': 'Research notes',
    'research_notes_subtitle': 'Record assumptions and findings',
    'research_sources': 'Research sources',
    'research_sources_subtitle': 'Attach links, reports, and interviews',
    'next_review': 'Next review',
    'not_scheduled': 'Not scheduled',
    'summary': 'Summary',
    'problem': 'Problem',
    'proposed_solution': 'Proposed solution',
    'target_users': 'Target users',
    'paying_customer': 'Paying customer',
    'created': 'Created',
    'updated': 'Updated',
    'not_added_yet': 'Not added yet',
    'overall_confidence': 'Overall confidence',
    'weakest_signal': 'Weakest signal',
    'next_experiment': 'Next experiment',
    'create_assumption_radar': 'Create assumption radar',
    'critical_assumptions': 'Critical assumptions',
    'tap_to_change_confidence': 'Tap an assumption to change confidence',
    'untested': 'Untested',
    'weak': 'Weak',
    'uncertain': 'Uncertain',
    'supported': 'Supported',
    'strong': 'Strong',
    'cancel': 'Cancel',
    'remove': 'Remove',
    'delete': 'Delete',
    'select_next_review_date': 'Select next review date',
    'remove_review_date': 'Remove review date',
    'remove_review_date_question': 'Remove review date?',
    'remove_review_date_desc': 'The idea will no longer appear in the next review schedule.',
    'archive_idea_question': 'Archive idea?',
    'restore_idea_question': 'Restore idea?',
    'archive_idea_desc': 'The idea will move to the archive. You can restore it later.',
    'restore_idea_desc': 'The idea will return to the active dashboard.',
    'delete_idea_question': 'Delete idea?',
    'delete_idea_desc': 'This idea will be permanently deleted. This action cannot be undone.',
    'ideas_load_error': 'Ideas could not be loaded.',
    'idea_save_error': 'The idea could not be saved.',
    'idea_update_error': 'The idea could not be updated.',
    'idea_delete_error': 'The idea could not be deleted.',
    'idea_deleted': 'Idea deleted.',
    'search_requires_idea': 'Add an active idea before searching.',
  },
  'ro': {
    'app_title': 'Idea Tracker',
    'tagline': 'De la idee la oportunitate.',
    'tagline_detail': 'Capturează, evaluează și dezvoltă ideile pe baza dovezilor.',
    'overview': 'Prezentare generală',
    'all_ideas': 'Toate ideile',
    'validated': 'Validate',
    'ideas': 'Idei',
    'of': 'din',
    'review': 'Revizuire',
    'new_idea': 'Idee nouă',
    'archived_ideas': 'Idei arhivate',
    'filter_sort': 'Filtrează și sortează ideile',
    'search_ideas': 'Caută idei',
    'language': 'Limbă',
    'english': 'English',
    'romanian': 'Română',
    'idea_radar_ready': 'Radarul ideilor este pregătit',
    'add_first_idea_desc': 'Adaugă prima idee și evaluează-i potențialul.',
    'add_first_idea': 'Adaugă prima idee',
    'no_filter_results': 'Nicio idee nu corespunde acestor filtre.',
    'clear_filters': 'Șterge filtrele',
    'try_again': 'Încearcă din nou',
    'idea_details': 'Detaliile ideii',
    'edit_idea': 'Editează ideea',
    'more_actions': 'Mai multe acțiuni',
    'archive_idea': 'Arhivează ideea',
    'restore_idea': 'Restaurează ideea',
    'archive': 'Arhivează',
    'restore': 'Restaurează',
    'delete_idea': 'Șterge ideea',
    'opportunity_score': 'Scorul oportunității',
    'not_evaluated': 'Neevaluată',
    'assumption_radar': 'Radarul ipotezelor',
    'assumption_radar_subtitle': 'Vezi ce mai trebuie demonstrat',
    'research_notes': 'Notițe de cercetare',
    'research_notes_subtitle': 'Înregistrează ipotezele și constatările',
    'research_sources': 'Surse de cercetare',
    'research_sources_subtitle': 'Atașează linkuri, rapoarte și interviuri',
    'next_review': 'Următoarea revizuire',
    'not_scheduled': 'Neprogramată',
    'summary': 'Rezumat',
    'problem': 'Problemă',
    'proposed_solution': 'Soluția propusă',
    'target_users': 'Utilizatori țintă',
    'paying_customer': 'Client plătitor',
    'created': 'Creată',
    'updated': 'Actualizată',
    'not_added_yet': 'Nu a fost adăugat încă',
    'overall_confidence': 'Nivel general de încredere',
    'weakest_signal': 'Cel mai slab semnal',
    'next_experiment': 'Următorul experiment',
    'create_assumption_radar': 'Creează radarul ipotezelor',
    'critical_assumptions': 'Ipoteze critice',
    'tap_to_change_confidence': 'Atinge o ipoteză pentru a modifica nivelul de încredere',
    'untested': 'Netestat',
    'weak': 'Slab',
    'uncertain': 'Incert',
    'supported': 'Susținut',
    'strong': 'Puternic',
    'cancel': 'Anulează',
    'remove': 'Elimină',
    'delete': 'Șterge',
    'select_next_review_date': 'Selectează data următoarei revizuiri',
    'remove_review_date': 'Elimină data revizuirii',
    'remove_review_date_question': 'Eliminăm data revizuirii?',
    'remove_review_date_desc': 'Ideea nu va mai apărea în programul următoarelor revizuiri.',
    'archive_idea_question': 'Arhivăm ideea?',
    'restore_idea_question': 'Restaurăm ideea?',
    'archive_idea_desc': 'Ideea va fi mutată în arhivă. O poți restaura ulterior.',
    'restore_idea_desc': 'Ideea va reveni în tabloul activ.',
    'delete_idea_question': 'Ștergem ideea?',
    'delete_idea_desc': 'Ideea va fi ștearsă definitiv. Această acțiune nu poate fi anulată.',
    'ideas_load_error': 'Ideile nu au putut fi încărcate.',
    'idea_save_error': 'Ideea nu a putut fi salvată.',
    'idea_update_error': 'Ideea nu a putut fi actualizată.',
    'idea_delete_error': 'Ideea nu a putut fi ștearsă.',
    'idea_deleted': 'Ideea a fost ștearsă.',
    'search_requires_idea': 'Adaugă o idee activă înainte de căutare.',
  },
};
