import 'package:flutter/material.dart';
import 'package:idearadar/app/localization/app_localization.dart';
import 'package:idearadar/features/problems/domain/problem.dart';

String ptx(BuildContext context, String key) {
  final code = Localizations.localeOf(context).languageCode;
  return (_problemTranslations[code] ?? _problemTranslations['en']!)[key] ??
      tr(context, key);
}

String localizedProblemStatus(BuildContext context, ProblemStatus status) =>
    switch (status) {
      ProblemStatus.observed => ptx(context, 'problem_status_observed'),
      ProblemStatus.researching => ptx(context, 'problem_status_researching'),
      ProblemStatus.validated => ptx(context, 'problem_status_validated'),
      ProblemStatus.parked => ptx(context, 'problem_status_parked'),
      ProblemStatus.rejected => ptx(context, 'problem_status_rejected'),
    };

const _problemTranslations = <String, Map<String, String>>{
  'en': {
    'problems': 'Problems',
    'problems_subtitle': 'Capture real problems before deciding what to build.',
    'new_problem': 'New problem',
    'edit_problem': 'Edit problem',
    'problem_title': 'Problem',
    'problem_title_hint': 'What real problem did you observe?',
    'problem_description': 'Description',
    'problem_description_hint': 'Describe what happens and why it matters',
    'affected_users': 'Who has this problem?',
    'affected_users_hint': 'People, organizations, or customer group',
    'frequency': 'How often does it happen?',
    'frequency_hint': 'Daily, weekly, occasionally...',
    'severity': 'How serious is it?',
    'severity_hint': 'What does the problem cost in time, money, or frustration?',
    'current_workaround': 'How is it solved today?',
    'current_workaround_hint': 'Existing workaround, tool, or manual process',
    'problem_evidence': 'Evidence / observations',
    'problem_evidence_hint': 'Interviews, examples, repeated observations, numbers...',
    'problem_status': 'Status',
    'problem_status_observed': 'Observed',
    'problem_status_researching': 'Researching',
    'problem_status_validated': 'Validated',
    'problem_status_parked': 'Parked',
    'problem_status_rejected': 'Rejected',
    'save_problem': 'Save problem',
    'save_changes': 'Save changes',
    'no_problems': 'No problems yet',
    'no_problems_desc': 'Capture a real problem before jumping to a solution.',
    'problems_load_error': 'Problems could not be loaded.',
    'problem_save_error': 'The problem could not be saved.',
    'problem_delete_error': 'The problem could not be deleted.',
    'delete_problem': 'Delete problem',
    'delete_problem_confirm': 'Delete this problem?',
    'delete_problem_desc': 'The problem and its links will be permanently deleted.',
    'problem_details': 'Problem details',
    'create_question_from_problem': 'Create question',
    'create_idea_from_problem': 'Create idea',
    'linked_questions': 'Linked questions',
    'linked_ideas': 'Linked ideas',
    'no_linked_questions': 'No linked questions yet',
    'no_linked_ideas': 'No linked ideas yet',
    'active_problems': 'Active',
    'today': 'Today',
    'more_actions': 'More actions',
  },
  'ro': {
    'problems': 'Probleme',
    'problems_subtitle': 'Notează probleme reale înainte să decizi ce construiești.',
    'new_problem': 'Problemă nouă',
    'edit_problem': 'Editează problema',
    'problem_title': 'Problemă',
    'problem_title_hint': 'Ce problemă reală ai observat?',
    'problem_description': 'Descriere',
    'problem_description_hint': 'Descrie ce se întâmplă și de ce contează',
    'affected_users': 'Cine are această problemă?',
    'affected_users_hint': 'Persoane, organizații sau grupul de clienți',
    'frequency': 'Cât de des apare?',
    'frequency_hint': 'Zilnic, săptămânal, ocazional...',
    'severity': 'Cât de serioasă este?',
    'severity_hint': 'Ce cost are în timp, bani sau frustrare?',
    'current_workaround': 'Cum este rezolvată astăzi?',
    'current_workaround_hint': 'Soluția actuală, instrumentul sau procesul manual',
    'problem_evidence': 'Dovezi / observații',
    'problem_evidence_hint': 'Interviuri, exemple, observații repetate, cifre...',
    'problem_status': 'Statut',
    'problem_status_observed': 'Observată',
    'problem_status_researching': 'În cercetare',
    'problem_status_validated': 'Validată',
    'problem_status_parked': 'În așteptare',
    'problem_status_rejected': 'Respinsă',
    'save_problem': 'Salvează problema',
    'save_changes': 'Salvează modificările',
    'no_problems': 'Nu există încă probleme',
    'no_problems_desc': 'Notează o problemă reală înainte să sari direct la soluție.',
    'problems_load_error': 'Problemele nu au putut fi încărcate.',
    'problem_save_error': 'Problema nu a putut fi salvată.',
    'problem_delete_error': 'Problema nu a putut fi ștearsă.',
    'delete_problem': 'Șterge problema',
    'delete_problem_confirm': 'Ștergem această problemă?',
    'delete_problem_desc': 'Problema și legăturile ei vor fi șterse definitiv.',
    'problem_details': 'Detaliile problemei',
    'create_question_from_problem': 'Creează întrebare',
    'create_idea_from_problem': 'Creează idee',
    'linked_questions': 'Întrebări asociate',
    'linked_ideas': 'Idei asociate',
    'no_linked_questions': 'Nu există încă întrebări asociate',
    'no_linked_ideas': 'Nu există încă idei asociate',
    'active_problems': 'Active',
    'today': 'Astăzi',
    'more_actions': 'Mai multe acțiuni',
  },
};
